# Generated by Django 2.1.1 on 2020-12-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('original', models.TextField(verbose_name=200)),
                ('shorts', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
    ]
